language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Codedeploy는 jar파일을 인식 못하므로 jar파일과 기타 설정들을 모아 압축한다.
before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 것만 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/ #scripts폴더의 deploy.sh 디렉토리에 복사
  - cp appspec.yml before-deploy/ #appspec.yml 디렉토리에 복사
  - cp build/libs/*.jar before-deploy/ # jar파일 디렉토리에 복사
  - cd before-deploy && zip -r before-deploy * #before-deploy디렉토리 이동 후 모두 압축
  - cd ../ && mkdir -p deploy #상위로 이동 후 deploy디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice.zip #zip파일 deploy디렉토리로 옮기기

# S3에 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: book-springboot-build-se # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: book-springboot-build-se # S3 버킷
    key: springboot-webservice.zip # 빌드파일 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springboot-webservice # 웹 콘솔에서 등록한 codedeploy 어플리케이션
    deployment_group: book-springboot-webservice-group # 웹 콘솔에서 등록한 codedeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - senyvee9@gmail.com
