version: 0.0
os: linux
files:
  - source: /
    destination:  /home/ec2-user/app/step2/zip/
    overwrite: yes

#codedeploy에서 넘겨준 파일들이 ec2-user권한을 가지도록
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  
# 배포단계에서 실행명령, ApplicationStart 단계에서 deploy.sh를 ec2-user권한으로 실행하게 함, 실행 후 60초를 기다리고 60초 이상 수행 시 실패
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
    